class_distribution:
  0: 4664
  1: 5350
  2: 1299
  3: 2155
  4: 1933
  5: 568
class_weights:
  0: 3.4239
  1: 2.9849
  2: 12.2933
  3: 7.4102
  4: 8.2613
  5: 28.1144
num_classes: 6
num_samples: 15969
